{"uid":"b7aca8cc7cc1f917","name":"test_dynamic_labels","fullName":"tests.test_labels#test_dynamic_labels","historyId":"ccd01939447b33c000e3c641ad15f597","time":{"start":1697454998334,"stop":1697454998334,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 118\nCurrent browser version is 117.0.5938.132 with binary path /opt/google/chrome/chrome\nStacktrace:\n#0 0x562c3607dfb3 <unknown>\n#1 0x562c35d514a7 <unknown>\n#2 0x562c35d8995b <unknown>\n#3 0x562c35d88c1a <unknown>\n#4 0x562c35d83acf <unknown>\n#5 0x562c35d8110c <unknown>\n#6 0x562c35dc3ac6 <unknown>\n#7 0x562c35dba713 <unknown>\n#8 0x562c35d8d18b <unknown>\n#9 0x562c35d8df7e <unknown>\n#10 0x562c360438d8 <unknown>\n#11 0x562c36047800 <unknown>\n#12 0x562c36051cfc <unknown>\n#13 0x562c36048418 <unknown>\n#14 0x562c3601542f <unknown>\n#15 0x562c3606c4e8 <unknown>\n#16 0x562c3606c6b4 <unknown>\n#17 0x562c3607d143 <unknown>\n#18 0x7f26b1a94b43 <unknown>","statusTrace":"self = <allure_commons._allure.fixture object at 0x7f3ff55d9350>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:23: in browser_management\n    browser.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1205: in quit\n    self.driver.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1100: in driver\n    return self.config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:343: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:171: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:93: in install_and_build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:205: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:289: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f3ff55dfbd0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: This version of Chro...\\\\n#16 0x562c3606c6b4 \\\\u003Cunknown>\\\\n#17 0x562c3607d143 \\\\u003Cunknown>\\\\n#18 0x7f26b1a94b43 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 118\nE       Current browser version is 117.0.5938.132 with binary path /opt/google/chrome/chrome\nE       Stacktrace:\nE       #0 0x562c3607dfb3 <unknown>\nE       #1 0x562c35d514a7 <unknown>\nE       #2 0x562c35d8995b <unknown>\nE       #3 0x562c35d88c1a <unknown>\nE       #4 0x562c35d83acf <unknown>\nE       #5 0x562c35d8110c <unknown>\nE       #6 0x562c35dc3ac6 <unknown>\nE       #7 0x562c35dba713 <unknown>\nE       #8 0x562c35d8d18b <unknown>\nE       #9 0x562c35d8df7e <unknown>\nE       #10 0x562c360438d8 <unknown>\nE       #11 0x562c36047800 <unknown>\nE       #12 0x562c36051cfc <unknown>\nE       #13 0x562c36048418 <unknown>\nE       #14 0x562c3601542f <unknown>\nE       #15 0x562c3606c4e8 <unknown>\nE       #16 0x562c3606c6b4 <unknown>\nE       #17 0x562c3607d143 <unknown>\nE       #18 0x7f26b1a94b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser_management","time":{"start":1697454998333,"stop":1697454998333,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 118\nCurrent browser version is 117.0.5938.132 with binary path /opt/google/chrome/chrome\nStacktrace:\n#0 0x562c3607dfb3 <unknown>\n#1 0x562c35d514a7 <unknown>\n#2 0x562c35d8995b <unknown>\n#3 0x562c35d88c1a <unknown>\n#4 0x562c35d83acf <unknown>\n#5 0x562c35d8110c <unknown>\n#6 0x562c35dc3ac6 <unknown>\n#7 0x562c35dba713 <unknown>\n#8 0x562c35d8d18b <unknown>\n#9 0x562c35d8df7e <unknown>\n#10 0x562c360438d8 <unknown>\n#11 0x562c36047800 <unknown>\n#12 0x562c36051cfc <unknown>\n#13 0x562c36048418 <unknown>\n#14 0x562c3601542f <unknown>\n#15 0x562c3606c4e8 <unknown>\n#16 0x562c3606c6b4 <unknown>\n#17 0x562c3607d143 <unknown>\n#18 0x7f26b1a94b43 <unknown>","statusTrace":"self = <allure_commons._allure.fixture object at 0x7f3ff55d9350>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:23: in browser_management\n    browser.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1205: in quit\n    self.driver.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1100: in driver\n    return self.config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:343: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:171: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:93: in install_and_build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:205: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:289: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f3ff55dfbd0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: This version of Chro...\\\\n#16 0x562c3606c6b4 \\\\u003Cunknown>\\\\n#17 0x562c3607d143 \\\\u003Cunknown>\\\\n#18 0x7f26b1a94b43 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 118\nE       Current browser version is 117.0.5938.132 with binary path /opt/google/chrome/chrome\nE       Stacktrace:\nE       #0 0x562c3607dfb3 <unknown>\nE       #1 0x562c35d514a7 <unknown>\nE       #2 0x562c35d8995b <unknown>\nE       #3 0x562c35d88c1a <unknown>\nE       #4 0x562c35d83acf <unknown>\nE       #5 0x562c35d8110c <unknown>\nE       #6 0x562c35dc3ac6 <unknown>\nE       #7 0x562c35dba713 <unknown>\nE       #8 0x562c35d8d18b <unknown>\nE       #9 0x562c35d8df7e <unknown>\nE       #10 0x562c360438d8 <unknown>\nE       #11 0x562c36047800 <unknown>\nE       #12 0x562c36051cfc <unknown>\nE       #13 0x562c36048418 <unknown>\nE       #14 0x562c3601542f <unknown>\nE       #15 0x562c3606c4e8 <unknown>\nE       #16 0x562c3606c6b4 <unknown>\nE       #17 0x562c3607d143 <unknown>\nE       #18 0x7f26b1a94b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","steps":[],"attachments":[{"uid":"b56b5235e3f75b01","name":"stderr","source":"b56b5235e3f75b01.txt","type":"text/plain","size":258}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"browser_management::0","time":{"start":1697454998334,"stop":1697454999301,"duration":967},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 118\nCurrent browser version is 117.0.5938.132 with binary path /opt/google/chrome/chrome\nStacktrace:\n#0 0x562c3607dfb3 <unknown>\n#1 0x562c35d514a7 <unknown>\n#2 0x562c35d8995b <unknown>\n#3 0x562c35d88c1a <unknown>\n#4 0x562c35d83acf <unknown>\n#5 0x562c35d8110c <unknown>\n#6 0x562c35dc3ac6 <unknown>\n#7 0x562c35dba713 <unknown>\n#8 0x562c35d8d18b <unknown>\n#9 0x562c35d8df7e <unknown>\n#10 0x562c360438d8 <unknown>\n#11 0x562c36047800 <unknown>\n#12 0x562c36051cfc <unknown>\n#13 0x562c36048418 <unknown>\n#14 0x562c3601542f <unknown>\n#15 0x562c3606c4e8 <unknown>\n#16 0x562c3606c6b4 <unknown>\n#17 0x562c3607d143 <unknown>\n#18 0x7f26b1a94b43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/qa_guru_python_7/qa_guru_python_7/tests/conftest.py\", line 23, in browser_management\n    browser.quit()\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1205, in quit\n    self.driver.quit()\n    ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1100, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 343, in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 171, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 93, in install_and_build_chrome\n    return Chrome(\n           ^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"tag","value":"web"},{"name":"severity","value":"blocker"},{"name":"feature","value":"Tasks in the repository"},{"name":"story","value":"Unauthorized user can't create an issue in the repository"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_labels"},{"name":"host","value":"fv-az244-344"},{"name":"thread","value":"2246-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_labels"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[{"name":"Testing","url":"https://github.com","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"blocker","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":2,"unknown":0,"total":6},"items":[{"uid":"bc3e5fff30f6566c","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/10//#testresult/bc3e5fff30f6566c","status":"broken","statusDetails":"ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)","time":{"start":1697444619970,"stop":1697444619970,"duration":0}},{"uid":"2d3399ca87d4f047","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/9//#testresult/2d3399ca87d4f047","status":"passed","time":{"start":1688982500814,"stop":1688982500814,"duration":0}},{"uid":"bfe7d2722d0ffc6a","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/8//#testresult/bfe7d2722d0ffc6a","status":"passed","time":{"start":1688981953109,"stop":1688981953109,"duration":0}},{"uid":"936b83f5e4e9e577","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/7//#testresult/936b83f5e4e9e577","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55acc05994e3 <unknown>\n#1 0x55acc02c8c76 <unknown>\n#2 0x55acc02f1d78 <unknown>\n#3 0x55acc02ee029 <unknown>\n#4 0x55acc032cccc <unknown>\n#5 0x55acc032c47f <unknown>\n#6 0x55acc0323de3 <unknown>\n#7 0x55acc02f92dd <unknown>\n#8 0x55acc02fa34e <unknown>\n#9 0x55acc05593e4 <unknown>\n#10 0x55acc055d3d7 <unknown>\n#11 0x55acc0567b20 <unknown>\n#12 0x55acc055e023 <unknown>\n#13 0x55acc052c1aa <unknown>\n#14 0x55acc05826b8 <unknown>\n#15 0x55acc0582847 <unknown>\n#16 0x55acc0592243 <unknown>\n#17 0x7f65edfd0b43 <unknown>","time":{"start":1688980171204,"stop":1688980171204,"duration":0}},{"uid":"46b8060ce6021620","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/5//#testresult/46b8060ce6021620","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x559b9b80c4e3 <unknown>\n#1 0x559b9b53bc76 <unknown>\n#2 0x559b9b564d78 <unknown>\n#3 0x559b9b561029 <unknown>\n#4 0x559b9b59fccc <unknown>\n#5 0x559b9b59f47f <unknown>\n#6 0x559b9b596de3 <unknown>\n#7 0x559b9b56c2dd <unknown>\n#8 0x559b9b56d34e <unknown>\n#9 0x559b9b7cc3e4 <unknown>\n#10 0x559b9b7d03d7 <unknown>\n#11 0x559b9b7dab20 <unknown>\n#12 0x559b9b7d1023 <unknown>\n#13 0x559b9b79f1aa <unknown>\n#14 0x559b9b7f56b8 <unknown>\n#15 0x559b9b7f5847 <unknown>\n#16 0x559b9b805243 <unknown>\n#17 0x7fdd9a49eb43 <unknown>","time":{"start":1688978996499,"stop":1688978996499,"duration":0}}]},"tags":["web"]},"source":"b7aca8cc7cc1f917.json","parameterValues":[]}